using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sunrise.UserInterface.Systems.Ghost.Controls.Roles
{
    [GenerateTypedNameReferences]
    public sealed partial class EventInfoBox : BoxContainer
    {
        private bool _descriptionVisible = true;
        private string _originalDescription = string.Empty;
        private Label? _hiddenDescriptionLabel;

        public EventInfoBox(string name, string description)
        {
            RobustXamlLoader.Load(this);

            Title.Text = name;
            _originalDescription = description;
            Description.SetMessage(description);

            // Sunrise-Start: метка для скрытого описания
            _hiddenDescriptionLabel = new Label
            {
                Text = "Описание скрыто. Нажмите, чтобы раскрыть.",
                Margin = new Thickness(0, 4)
            };
            _hiddenDescriptionLabel.Visible = false;
            AddChild(_hiddenDescriptionLabel);

            // Контейнер кнопки только на описание (название всегда видно)
            var wrapper = new ContainerButton { HorizontalExpand = true };
            RemoveChild(DividerPanel);
            RemoveChild(Description);
            wrapper.AddChild(DividerPanel);
            wrapper.AddChild(Description);
            AddChild(wrapper);
            wrapper.OnPressed += ToggleDescription;
            // Sunrise-End
        }

        private void ToggleDescription(BaseButton.ButtonEventArgs args)
        {
            _descriptionVisible = !_descriptionVisible;
            
            if (_descriptionVisible)
            {
                // Показываем оригинальное описание
                Description.Visible = true;
                DividerPanel.Visible = true;
                if (_hiddenDescriptionLabel != null)
                    _hiddenDescriptionLabel.Visible = false;
            }
            else
            {
                // Скрываем описание, показываем метку
                Description.Visible = false;
                DividerPanel.Visible = false;
                if (_hiddenDescriptionLabel != null)
                    _hiddenDescriptionLabel.Visible = true;
            }
        }
    }
}

