using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Sunrise.UserInterface.Systems.Ghost.Controls.Roles;

[GenerateTypedNameReferences]
public sealed partial class EventEntryButtons : BoxContainer
{
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IClientConsoleHost _consoleHost = default!;

    private int _currentParticipants = 0;
    private int _maxParticipants = 1;
    private int _confirmedParticipants = 0;
    private bool _isParticipating = false;
    private bool _isReady = false;
    private bool _isConfirmed = false;
    private bool _isEventActive = false;
    private TimeSpan? _countdownEndTime = null;
    private TimeSpan? _eventStartTime = null;
    
    public int GetConfirmedCount() => _confirmedParticipants;

    public event Action? OnDetailsButtonPressed;
    public event Action? OnConfirmButtonPressed;

    public EventEntryButtons()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        DetailsButton.OnPressed += OnDetailsButtonClick;
        UpdateButtons();
    }

    private void OnDetailsButtonClick(BaseButton.ButtonEventArgs args)
    {
        if (_isReady)
        {
            _isConfirmed = true;
            OnConfirmButtonPressed?.Invoke();
        }
        else
        {
            OnDetailsButtonPressed?.Invoke();
        }
    }

    public void SetParticipants(int current, int max, int confirmed = 0)
    {
        _currentParticipants = current;
        _maxParticipants = max;
        _confirmedParticipants = confirmed;
        UpdateButtons();
    }
    
    public void SetConfirmed(int confirmed)
    {
        _confirmedParticipants = confirmed;
        UpdateButtons();
    }
    
    public void SetEventActive(bool active, TimeSpan? startTime = null)
    {
        _isEventActive = active;
        if (active && startTime.HasValue)
        {
            _eventStartTime = startTime;
        }
        UpdateButtons();
    }

    public void SetParticipating(bool participating)
    {
        _isParticipating = participating;
        UpdateButtons();
    }

    public void SetReady(bool ready)
    {
        _isReady = ready;
        _isConfirmed = false;

        if (ready)
        {
            _countdownEndTime = _timing.CurTime + TimeSpan.FromSeconds(10);
            TimerButton.Visible = true;
        }
        else
        {
            _countdownEndTime = null;
            TimerButton.Visible = false;
            TimerButton.Text = string.Empty;
        }

        UpdateButtons();
    }

    private void UpdateButtons()
    {
        if (_isEventActive)
        {
            // Ивент активен
            ParticipantsButton.Text = $"{_currentParticipants}/{_maxParticipants} ({_confirmedParticipants}/{_maxParticipants})";
            DetailsButton.Text = "Ивент активен";
            TimerButton.Visible = true;
            TimerButton.StyleClasses.Clear();
            TimerButton.StyleClasses.Add("OpenBoth");
        }
        else if (_isReady)
        {
            // Ожидание подтверждения
            ParticipantsButton.Text = $"{_currentParticipants}/{_maxParticipants} ({_confirmedParticipants}/{_maxParticipants})";
            DetailsButton.Text = "Подтвердить готовность";
            TimerButton.Visible = true;
            TimerButton.StyleClasses.Clear();
            TimerButton.StyleClasses.Add("OpenBoth");
        }
        else
        {
            // Обычное состояние
            ParticipantsButton.Text = $"{_currentParticipants}/{_maxParticipants}";
            DetailsButton.Text = "Подробнее";
            TimerButton.Visible = false;
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_isEventActive && _eventStartTime.HasValue)
        {
            // Таймер с начала ивента (минуты:секунды)
            var elapsed = _timing.CurTime - _eventStartTime.Value;
            var totalSeconds = (int)elapsed.TotalSeconds;
            var minutes = totalSeconds / 60;
            var seconds = totalSeconds % 60;
            TimerButton.Text = $"{minutes}:{seconds:00}";
        }
        else if (_isReady && _countdownEndTime.HasValue)
        {
            // Таймер обратного отсчета
            var timeLeft = _countdownEndTime.Value - _timing.CurTime;

            if (timeLeft > TimeSpan.Zero)
            {
                var timeString = $"{timeLeft.Minutes:00}:{timeLeft.Seconds:00}";
                TimerButton.Text = timeString;
            }
            else
            {
                // Таймер закончился - ивент начинается
                TimerButton.Visible = false;
                _countdownEndTime = null;
                
                // Проверяем, достаточно ли подтверждений
                if (_confirmedParticipants >= _maxParticipants)
                {
                    SetEventActive(true, _timing.CurTime);
                }
            }
        }
    }
}

