using System.Linq;
using Content.Client.UserInterface.Systems.Ghost.Controls.Roles; // Импорт для GhostRoleInfoBox
using Content.Shared.Ghost.Roles;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Sunrise.UserInterface.Systems.Ghost.Controls.Roles
{
    [GenerateTypedNameReferences]
    public sealed partial class EventDetailsWindow : DefaultWindow
    {
        public event Action<GhostRoleInfo>? OnRoleSelected;
        // Sunrise-Start: событие для автоматического участия при выборе приоритета
        public event Action? OnPriorityChanged;
        // Sunrise-End

        // Sunrise-Start: отслеживание приоритетов ролей
        private Dictionary<GhostRoleInfo, JobPriority> _rolePriorities = new();
        private Dictionary<GhostRoleInfo, Dictionary<JobPriority, Button>> _priorityButtons = new();
        // Sunrise-End

        public EventDetailsWindow()
        {
            RobustXamlLoader.Load(this);
            
            // Sunrise-Start: обработчик кнопки сброса приоритетов
            ResetPrioritiesButton.OnPressed += _ => ResetAllPriorities();
            // Sunrise-End
        }

        public void AddRole(GhostRoleInfo role, SpriteSystem spriteSystem)
        {
            var info = new GhostRoleInfoBox(role.Name, role.Description);
            
            // Sunrise-Start: кнопки приоритетов
            var priorityContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 4, 0, 4)
            };

            var priorityButtons = new Dictionary<JobPriority, Button>();
            var priorities = new[] { JobPriority.Never, JobPriority.Low, JobPriority.Medium, JobPriority.High };
            var priorityTexts = new[] { "Никогда", "Низкий", "Средний", "Высокий" };

            _rolePriorities[role] = JobPriority.Never; // По умолчанию "Никогда"

            for (int i = 0; i < priorities.Length; i++)
            {
                var priority = priorities[i];
                var button = new Button
                {
                    Text = priorityTexts[i],
                    HorizontalExpand = true,
                    SizeFlagsStretchRatio = 1
                };

                // Стили для кнопок
                if (i == 0)
                    button.StyleClasses.Add("OpenRight");
                else if (i == priorities.Length - 1)
                    button.StyleClasses.Add("OpenLeft");
                else
                    button.StyleClasses.Add("OpenBoth");

                // По умолчанию активна кнопка "Никогда" (темный цвет)
                if (priority == JobPriority.Never)
                {
                    button.Pressed = true;
                    UpdateButtonStyle(button, true);
                }

                var capturedPriority = priority;
                button.OnPressed += _ =>
                {
                    OnPrioritySelected(role, capturedPriority, priorityButtons);
                };

                priorityButtons[priority] = button;
                priorityContainer.AddChild(button);
            }

            _priorityButtons[role] = priorityButtons;
            // Sunrise-End

            var takeButton = new Button
            {
                Text = "Занять место",
                HorizontalExpand = true
            };

            takeButton.OnPressed += _ =>
            {
                OnRoleSelected?.Invoke(role);
            };

            var container = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(0, 0, 0, 8)
            };

            container.AddChild(info);
            // Sunrise-Start: добавляем кнопки приоритетов
            container.AddChild(priorityContainer);
            // Sunrise-End
            // Убрали кнопку "Занять место" - участие автоматически при выборе приоритета
            RolesContainer.AddChild(container);
        }

        // Sunrise-Start: обработка выбора приоритета
        private void OnPrioritySelected(GhostRoleInfo role, JobPriority selectedPriority, Dictionary<JobPriority, Button> buttons)
        {
            // Если выбран "Высокий", сбрасываем все остальные "Высокий" на "Средний"
            if (selectedPriority == JobPriority.High)
            {
                foreach (var (otherRole, otherButtons) in _priorityButtons)
                {
                    if (otherRole.Identifier == role.Identifier)
                        continue;

                    if (_rolePriorities[otherRole] == JobPriority.High)
                    {
                        _rolePriorities[otherRole] = JobPriority.Medium;
                        UpdatePriorityButtons(otherRole, otherButtons, JobPriority.Medium);
                    }
                }
            }

            var oldPriority = _rolePriorities.GetValueOrDefault(role, JobPriority.Never);
            _rolePriorities[role] = selectedPriority;
            UpdatePriorityButtons(role, buttons, selectedPriority);

            // Если игрок выбрал любой приоритет кроме "Никогда" хотя бы для одной роли, автоматически участвует
            bool hasAnyNonNeverPriority = _rolePriorities.Values.Any(p => p != JobPriority.Never);
            if (hasAnyNonNeverPriority && (oldPriority == JobPriority.Never || selectedPriority != JobPriority.Never))
            {
                OnPriorityChanged?.Invoke();
            }
        }

        private void UpdatePriorityButtons(GhostRoleInfo role, Dictionary<JobPriority, Button> buttons, JobPriority selectedPriority)
        {
            foreach (var (priority, button) in buttons)
            {
                button.Pressed = priority == selectedPriority;
                UpdateButtonStyle(button, button.Pressed);
            }
        }

        private void UpdateButtonStyle(Button button, bool isActive)
        {
            // Темный цвет для активной кнопки
            if (isActive)
            {
                button.ModulateSelfOverride = Color.FromHex("#5a5a5a");
            }
            else
            {
                button.ModulateSelfOverride = null;
            }
        }
        // Sunrise-End

        // Sunrise-Start: сброс всех приоритетов
        private void ResetAllPriorities()
        {
            foreach (var (role, buttons) in _priorityButtons)
            {
                _rolePriorities[role] = JobPriority.Never;
                UpdatePriorityButtons(role, buttons, JobPriority.Never);
            }
        }
        // Sunrise-End

        public void ClearRoles()
        {
            RolesContainer.RemoveAllChildren();
            // Sunrise-Start: очистка приоритетов
            _rolePriorities.Clear();
            _priorityButtons.Clear();
            // Sunrise-End
        }
    }
}

