using System.Linq;
using Content.Client.UserInterface.Systems.Ghost.Controls.Roles;
using Content.Client.Ghost;
using Content.Shared.Ghost.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Sunrise.UserInterface.Systems.Ghost.Controls.Roles
{
    [GenerateTypedNameReferences]
    public sealed partial class SunriseGhostRolesWindow : DefaultWindow
    {

        public event Action<GhostRoleInfo>? OnRoleRequestButtonClicked;
        public event Action<GhostRoleInfo>? OnRoleRulesButtonClicked;
        public event Action<GhostRoleInfo>? OnRoleFollow;

        private Dictionary<string, Collapsible> _collapsibleBoxes = new();
        private HashSet<string> _uncollapsedStates = new();
        private int _currentView = 0; // 0 = Main, 1 = Events

        // Sunrise-Start: счетчики для вкладок
        private int _mainRolesCount = 0;
        private int _eventsCount = 0;
        
        [Dependency] private readonly GhostSystem _ghostSystem = default!;
        // Sunrise-End

        // Event state
        private EventDetailsWindow? _eventDetailsWindow;
        private EventEntryButtons? _currentEventButtons;

        public SunriseGhostRolesWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            MainTabButton.OnPressed += _ =>
            {
                MainTabButton.IsCurrent = true;
                EventsTabButton.IsCurrent = false;
                ChangeView(0);
            };

            EventsTabButton.OnPressed += _ =>
            {
                MainTabButton.IsCurrent = false;
                EventsTabButton.IsCurrent = true;
                ChangeView(1);
            };

            // Sunrise-Start: обновление счетчиков
            UpdateTabCounters();
            // Sunrise-End

            // Initialize events view with example event
            InitializeEventsView();
        }

        private void ChangeView(int view)
        {
            _currentView = view;
            MainView.Visible = view == 0;
            EventsView.Visible = view == 1;
        }

        public void ClearEntries()
        {
            NoRolesMessage.Visible = true;
            EntryContainer.RemoveAllChildren();
            _collapsibleBoxes.Clear();
        }

        public void SaveCollapsibleBoxesStates()
        {
            _uncollapsedStates.Clear();
            foreach (var (key, collapsible) in _collapsibleBoxes)
            {
                if (collapsible.BodyVisible)
                {
                    _uncollapsedStates.Add(key);
                }
            }
        }

        public void RestoreCollapsibleBoxesStates()
        {
            foreach (var (key, collapsible) in _collapsibleBoxes)
            {
                collapsible.BodyVisible = _uncollapsedStates.Contains(key);
            }
        }

        public void AddEntry(string name, string description, string prototypeId, bool hasAccess, FormattedMessage? reason, IEnumerable<GhostRoleInfo> roles, SpriteSystem spriteSystem)
        {
            NoRolesMessage.Visible = false;

            var ghostRoleInfos = roles.ToList();
            var rolesCount = ghostRoleInfos.Count;

            // Sunrise-Start: счетчик обновляется автоматически из GhostSystem
            UpdateTabCounters();
            // Sunrise-End

            var info = new GhostRoleInfoBox(name, description);
            var buttons = new GhostRoleButtonsBox(hasAccess, reason, ghostRoleInfos, spriteSystem);
            buttons.OnRoleSelected += OnRoleRequestButtonClicked;
            buttons.OnRoleRules += OnRoleRulesButtonClicked;
            buttons.OnRoleFollow += OnRoleFollow;

            EntryContainer.AddChild(info);

            if (rolesCount > 1)
            {
                var buttonHeading = new CollapsibleHeading(Loc.GetString("ghost-roles-window-available-button", ("rolesCount", rolesCount)));

                buttonHeading.AddStyleClass(ContainerButton.StyleClassButton);
                buttonHeading.Label.HorizontalAlignment = HAlignment.Center;
                buttonHeading.Label.HorizontalExpand = true;
                buttonHeading.Margin = new Thickness(8, 0, 8, 2);

                var body = new CollapsibleBody
                {
                    Margin = new Thickness(0, 5, 0, 0),
                };

                var collapsible = new Collapsible(buttonHeading, body)
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    Margin = new Thickness(0, 0, 0, 8),
                };

                body.AddChild(buttons);

                EntryContainer.AddChild(collapsible);
                _collapsibleBoxes.Add(prototypeId, collapsible);
            }
            else
            {
                EntryContainer.AddChild(buttons);
            }
        }

        private void InitializeEventsView()
        {
            // Create example event: Planet Prison
            var eventInfo = new EventInfoBox(
                "Планетарная тюрьма (ID:1)",
                "Планетарная тюрьма - место для отбывания наказания. Вы можете стать сотрудником тюрьмы или заключенным."
            );

            _currentEventButtons = new EventEntryButtons();
            _currentEventButtons.SetParticipants(0, 1);
            _currentEventButtons.OnDetailsButtonPressed += OnEventDetailsPressed;
            _currentEventButtons.OnConfirmButtonPressed += OnEventConfirmPressed;

            var container = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(0, 0, 0, 8)
            };

            container.AddChild(eventInfo);
            container.AddChild(_currentEventButtons);
            EventsContainer.AddChild(container);

            // Sunrise-Start: обновление счетчика ивентов
            _eventsCount = 1;
            UpdateTabCounters();
            // Sunrise-End
        }

        // Sunrise-Start: обновление счетчиков в кнопках вкладок
        private void UpdateTabCounters()
        {
            // Парсим число из AvailableGhostRoleCount вместо подсчета вручную
            var rolesCount = _ghostSystem.AvailableGhostRoleCount;
            MainTabButton.LabelText = rolesCount > 0 ? $"Главная ({rolesCount})" : "Главная";
            EventsTabButton.LabelText = _eventsCount > 0 ? $"Ивенты ({_eventsCount})" : "Ивенты";
        }
        // Sunrise-End

        private void OnEventDetailsPressed()
        {
            if (_eventDetailsWindow != null)
            {
                _eventDetailsWindow.Close();
            }

            _eventDetailsWindow = new EventDetailsWindow();
            _eventDetailsWindow.OnRoleSelected += OnEventRoleSelected;
            // Sunrise-Start: автоматическое участие при выборе приоритета
            _eventDetailsWindow.OnPriorityChanged += OnEventPriorityChanged;
            // Sunrise-End

            var spriteSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();

            // Добавляем все роли планетарной тюрьмы
            var prisonRoles = new[]
            {
                new GhostRoleInfo
                {
                    Identifier = 1001,
                    Name = Loc.GetString("ghost-role-information-planet-prison-head-name"),
                    Description = Loc.GetString("ghost-role-information-planet-prison-head-description"),
                    Rules = Loc.GetString("ghost-role-information-nonantagonist-rules"),
                    Kind = GhostRoleKind.FirstComeFirstServe,
                    PrototypeId = "RandomHumanoidPlanetPrisonHeadOfPrison"
                },
                new GhostRoleInfo
                {
                    Identifier = 1002,
                    Name = Loc.GetString("ghost-role-information-planet-prison-inspector-name"),
                    Description = Loc.GetString("ghost-role-information-planet-prison-inspector-description"),
                    Rules = Loc.GetString("ghost-role-information-nonantagonist-rules"),
                    Kind = GhostRoleKind.FirstComeFirstServe,
                    PrototypeId = "RandomHumanoidPlanetPrisonInspector"
                },
                new GhostRoleInfo
                {
                    Identifier = 1003,
                    Name = Loc.GetString("ghost-role-information-planet-prison-worker-name"),
                    Description = Loc.GetString("ghost-role-information-planet-prison-worker-description"),
                    Rules = Loc.GetString("ghost-role-information-nonantagonist-rules"),
                    Kind = GhostRoleKind.FirstComeFirstServe,
                    PrototypeId = "RandomHumanoidPlanetPrisonWorker"
                },
                new GhostRoleInfo
                {
                    Identifier = 1004,
                    Name = Loc.GetString("ghost-role-information-planet-prison-engineer-name"),
                    Description = Loc.GetString("ghost-role-information-planet-prison-engineer-description"),
                    Rules = Loc.GetString("ghost-role-information-nonantagonist-rules"),
                    Kind = GhostRoleKind.FirstComeFirstServe,
                    PrototypeId = "RandomHumanoidPlanetPrisonEngineer"
                },
                new GhostRoleInfo
                {
                    Identifier = 1005,
                    Name = Loc.GetString("ghost-role-information-planet-prison-scientist-name"),
                    Description = Loc.GetString("ghost-role-information-planet-prison-scientist-description"),
                    Rules = Loc.GetString("ghost-role-information-nonantagonist-rules"),
                    Kind = GhostRoleKind.FirstComeFirstServe,
                    PrototypeId = "RandomHumanoidPlanetPrisonScientist"
                },
                new GhostRoleInfo
                {
                    Identifier = 1006,
                    Name = Loc.GetString("ghost-role-information-planet-prison-doctor-name"),
                    Description = Loc.GetString("ghost-role-information-planet-prison-doctor-description"),
                    Rules = Loc.GetString("ghost-role-information-nonantagonist-rules"),
                    Kind = GhostRoleKind.FirstComeFirstServe,
                    PrototypeId = "RandomHumanoidPlanetPrisonDoctor"
                },
                new GhostRoleInfo
                {
                    Identifier = 1007,
                    Name = Loc.GetString("ghost-role-information-planet-prison-chef-name"),
                    Description = Loc.GetString("ghost-role-information-planet-prison-chef-description"),
                    Rules = Loc.GetString("ghost-role-information-nonantagonist-rules"),
                    Kind = GhostRoleKind.FirstComeFirstServe,
                    PrototypeId = "RandomHumanoidPlanetPrisonChef"
                },
                new GhostRoleInfo
                {
                    Identifier = 1008,
                    Name = Loc.GetString("ghost-role-information-planet-prison-prisoner-name"),
                    Description = Loc.GetString("ghost-role-information-planet-prison-prisoner-description"),
                    Rules = Loc.GetString("ghost-role-information-freeagent-rules"),
                    Kind = GhostRoleKind.FirstComeFirstServe,
                    PrototypeId = "RandomHumanoidPlanetPrisonPrisoner"
                }
            };

            foreach (var role in prisonRoles)
            {
                _eventDetailsWindow.AddRole(role, spriteSystem);
            }

            _eventDetailsWindow.OpenCentered();
        }

        private void OnEventRoleSelected(GhostRoleInfo role)
        {
            // Player selected a role in the event
            _currentEventButtons?.SetParticipating(true);
            _currentEventButtons?.SetParticipants(1, 1);
            _eventDetailsWindow?.Close();
            _eventDetailsWindow = null;

            // Start countdown and show "Подтвердить готовность"
            _currentEventButtons?.SetReady(true);
        }

        private void OnEventConfirmPressed()
        {
            // Игрок подтвердил готовность
            if (_currentEventButtons != null)
            {
                var currentConfirmed = _currentEventButtons.GetConfirmedCount();
                _currentEventButtons.SetConfirmed(currentConfirmed + 1);
            }
        }

        // Sunrise-Start: автоматическое участие при выборе приоритета
        private void OnEventPriorityChanged()
        {
            // Если игрок выбрал приоритет (не "Никогда"), автоматически участвует
            if (_currentEventButtons != null)
            {
                _currentEventButtons.SetParticipating(true);
                _currentEventButtons.SetParticipants(1, 1);
            }
        }
        // Sunrise-End

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);
            // Логика таймера и addgamerule теперь в EventEntryButtons
        }
    }
}

