using System.Linq;
using Content.Shared.Ghost.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
// Sunrise-Start
using Content.Client.PDA;
// Для GhostRoleInfoBox, GhostRoleButtonsBox, BoxContainer и Label
using Content.Client.UserInterface.Systems.Ghost.Controls.Roles;
// Sunrise-End

namespace Content.Client.UserInterface.Systems.Ghost.Controls.Roles
{
    [GenerateTypedNameReferences]
    public sealed partial class GhostRolesWindow : DefaultWindow
    {
        public event Action<GhostRoleInfo>? OnRoleRequestButtonClicked;
        public event Action<GhostRoleInfo>? OnRoleRulesButtonClicked;
        public event Action<GhostRoleInfo>? OnRoleFollow;

        private Dictionary<string, Collapsible> _collapsibleBoxes = new();
        private HashSet<string> _uncollapsedStates = new();

        public GhostRolesWindow()
        {
            RobustXamlLoader.Load(this);
            // Sunrise-Start: вкладки
            MainTabButton.OnPressed += _ =>
            {
                MainTabButton.IsCurrent = true;
                EventsTabButton.IsCurrent = false;
                EntryContainer.Visible = true;
                MainScrollContainer.Visible = true;
                EventsContainer.Visible = false;
                EventsScrollContainer.Visible = false;
            };
            EventsTabButton.OnPressed += _ =>
            {
                MainTabButton.IsCurrent = false;
                EventsTabButton.IsCurrent = true;
                EntryContainer.Visible = false;
                MainScrollContainer.Visible = false;
                EventsContainer.Visible = true;
                EventsScrollContainer.Visible = true;

                if (EventsContainer.ChildCount == 0)
                    AddEventDemoBox(); // hot reload: повторно не добавлять
            };
            // Sunrise-End
        }

        // Sunrise-Start: пример ивента
        private void AddEventDemoBox()
        {
            // Демонстрация ивента: "Скелет из шкафа"
            var eventInfo = new GhostRoleInfoBox("Скелет из шкафа", "Вы, похоже, один из старейших сотрудников станции! Верните себе прежнюю должность или устройте хаос! Мир в ваших руках.");

            var eventButtonRow = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
            var playersBtn = new Button
            {
                Text = "0/1",
                HorizontalExpand = true,
                SizeFlagsStretchRatio = 1
            };
            var detailsBtn = new Button
            {
                Text = "Подробнее",
                HorizontalExpand = true,
                SizeFlagsStretchRatio = 1
            };
            eventButtonRow.AddChild(playersBtn);
            eventButtonRow.AddChild(detailsBtn);

            var eventBox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical };
            eventBox.AddChild(eventInfo);
            eventBox.AddChild(eventButtonRow);
            EventsContainer.AddChild(eventBox);
            // Для теста можно повесить на detailsBtn событие открытия окна подробностей
        }
        // Sunrise-End

        public void ClearEntries()
        {
            NoRolesMessage.Visible = true;
            EntryContainer.RemoveAllChildren();
            _collapsibleBoxes.Clear();
        }

        public void SaveCollapsibleBoxesStates()
        {
            _uncollapsedStates.Clear();
            foreach (var (key, collapsible) in _collapsibleBoxes)
            {
                if (collapsible.BodyVisible)
                {
                    _uncollapsedStates.Add(key);
                }
            }
        }

        public void RestoreCollapsibleBoxesStates()
        {
            foreach (var (key, collapsible) in _collapsibleBoxes)
            {
                collapsible.BodyVisible = _uncollapsedStates.Contains(key);
            }
        }

        public void AddEntry(string name, string description, string prototypeId, bool hasAccess, FormattedMessage? reason, IEnumerable<GhostRoleInfo> roles, SpriteSystem spriteSystem)
        {
            NoRolesMessage.Visible = false;

            var ghostRoleInfos = roles.ToList();
            var rolesCount = ghostRoleInfos.Count;

            var info = new GhostRoleInfoBox(name, description);
            var buttons = new GhostRoleButtonsBox(hasAccess, reason, ghostRoleInfos, spriteSystem);
            buttons.OnRoleSelected += OnRoleRequestButtonClicked;
            buttons.OnRoleRules += OnRoleRulesButtonClicked;
            buttons.OnRoleFollow += OnRoleFollow;

            EntryContainer.AddChild(info);

            if (rolesCount > 1)
            {
                var buttonHeading = new CollapsibleHeading(Loc.GetString("ghost-roles-window-available-button", ("rolesCount", rolesCount)));

                buttonHeading.AddStyleClass(ContainerButton.StyleClassButton);
                buttonHeading.Label.HorizontalAlignment = HAlignment.Center;
                buttonHeading.Label.HorizontalExpand = true;
                buttonHeading.Margin = new Thickness(8, 0, 8, 2);

                var body = new CollapsibleBody
                {
                    Margin = new Thickness(0, 5, 0, 0),
                };

                var collapsible = new Collapsible(buttonHeading, body)
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    Margin = new Thickness(0, 0, 0, 8),
                };

                body.AddChild(buttons);

                EntryContainer.AddChild(collapsible);
                _collapsibleBoxes.Add(prototypeId, collapsible);
            }
            else
            {
                EntryContainer.AddChild(buttons);
            }
        }
    }
}
